#!/bin/sh
JS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")

PASS=true

# Check for eslint
if [[ "$JS_STAGED_FILES" != "" ]]; then
  echo "\nValidating Javascript:\n"

  node ./node_modules/.bin/eslint $JS_STAGED_FILES

  if [[ "$?" == 0 ]]; then
    echo "\033[32mESLint Passed\033[0m"
  else
    echo "\033[41mESLint Failed\033[0m"
    PASS=false
  fi

  echo "\nJavascript validation completed!\n"
fi

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint and Scss-lint but do not. Please fix the ESLint and Scss-lint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
